version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  install-deps:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn test
      - run: yarn e2e
workflows:
  test:
    jobs:
      - install-deps