on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    services:
      # Label used to access the service container
       postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.15
      uses: actions/setup-node@v2
      with:
        node-version: 14.15

    - name: yarn install, yarn test:coveralls 
      run: |
        yarn install
        yarn test:coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}